<?php    

$title="S-Cross | Maruti Suzuki NEXA Showroom in Nashik, Nagpur, Nanded | SEVA";	

?>
<?php 

 $pgDesc="Check New Maruti Suzuki S-Cross Price at SEVA Maruti Suzuki NEXA Car Showroom in Nashik, Nagpur, Nanded. Maruti Suzuki Nexa S Cross Car Price, Mileage, Images and More";

 $pgKeywords="nexa s cross, S cross, s cross price, suzuki s cross, maruti s cross, s cross car, s cross petrol, s cross on road price, s cross maruti suzuki, s cross 2020, Nexa Cars, Maruti Suzuki NEXA, Nashik, Nagpur, Nanded, NEXA, Maruti Nexa, Nexa Car, Maruti Nexa, Suzuki Nexa, nexa showroom, nexa showroom near me, nexa car price, nexa new car, nexa price, nexa experience, nexa near me, maruti nexa price, maruti nexa cars, maruti nexa showroom near me";

 include 'header.php'; 

?>
<style type="text/css">
.parsley-required {
	color: red;
}
.parsley-type {
	color: red;
}
.parsley-pattern {
	color: red;
}
.parsley-range {
	color: red;
}
</style>
<main>

<div class="generic-hero">
  <div class="itemimg">
    <picture>
      <source srcset="assets/images/s-cross/top-desk.jpg" alt="s-cross Car Banner" media="(min-width: 992px)">
      <source srcset="assets/images/s-cross/top-ipad.jpg" alt="s-cross Car Banner" media="(min-width: 768px)">
      <source srcset="assets/images/s-cross/top-mobile.jpg" alt="s-cross Car Banner" media="(min-width: 320px)">
      <img srcset="assets/images/s-cross/top-desk.jpg" alt="s-cross Car Banner"> </picture>
    <div class="mediacontent col-lg-5 white right vcenter"> <img src="assets/images/s-cross/2020scross.png" alt="S-Cross 2020">
      <div class="desktopcontent hidden-xs hidden-sm mt-2">
        <p style="color:#FFF"> The Maruti Suzuki S-Cross is a premium crossover that is sold through the NEXA retail chain. The car is powered by 1.3 L diesel engine. Power and torque generated by the 1.3 L motor is rated at 88.5 hp at 4,000 rpm and 200 Nm at 1,750 rpm. </p>
      </div>
      <div class="mobilecontent hidden-md hidden-lg">
        <p style="color:#FFF">The Maruti Suzuki S-Cross is a premium crossover that is sold through the NEXA retail chain.</p>
      </div>
    </div>
  </div>
</div>
<div class="mid-nav fixed-bottom">
  <ul>
    <li><a data-toggle="modal" data-target="#get-quotePopup">Get A Quote</a></li>
    <li><a href="test-drive.php">Book Test Drive</a></li>
    <li><a href="assets/images/s-cross/The-All-New-S-Cross.pdf" target="_blank">Product Brochure</a></li>
    <li><a href="nexa-finance.php">Finance</a></li>
  </ul>
</div>
<div class="product-carousel">
  <div class="item">
    <picture class="productcarouselbg">
      <source srcset="assets/images/s-cross/2-desk.jpg" alt="Ignis Car" media="(min-width: 992px)">
      <source srcset="assets/images/s-cross/2-ipad.jpg" alt="Ignis Car" media="(min-width: 768px)">
      <source srcset="assets/images/s-cross/2-mobile.jpg" alt="Ignis Car" media="(min-width: 320px)">
      <img srcset="assets/images/s-cross/2-desk.jpg" alt="Ignis Car" class="resposive-img productbg"> </picture>
    <div class="productItems Aligner">
      <div class="container-fluid rel">
        <div class="car-color-variant"> 
        <a onclick="color_function(1,5)" href="javascript:void(0);"><img src="assets/images/cc-darkblue.jpg"></a> 
        <a onclick="color_function(2,5)" href="javascript:void(0);"><img src="assets/images/cc-brown.jpg"></a> 
        <a onclick="color_function(3,5)" href="javascript:void(0);"><img src="assets/images/cc-magmagray.jpg"></a> 
        <a onclick="color_function(4,5)" href="javascript:void(0);"><img src="assets/images/cc-white.jpg"></a> 
        <a onclick="color_function(5,5)" href="javascript:void(0);"><img src="assets/images/cc-magna-gray.jpg"></a> 
        </div>
        <div class="row">
          <div class="col-lg-6">
           <img id="image_1" src="assets/images/s-cross/sc-Blue.png" class="resposive-img">
           <img id="image_2" src="assets/images/s-cross/sc-CAFFEINE-BROWN.png" style="display:none" class="resposive-img"> 
           <img id="image_3" src="assets/images/s-cross/sc-PREMIUM-SILVER.png" style="display:none" class="resposive-img"> 
           <img id="image_4" src="assets/images/s-cross/sc-white.png" style="display:none" class="resposive-img"> 
           <img id="image_5" src="assets/images/s-cross/sc-GRANITE-GREY.png" style="display:none" class="resposive-img"> 
           </div>
          <div class="col-lg-6">
            <div class="proudctFooter">
              <div class="col-lg-10">
                <div class="product-content">
                  <h3 class="terms mileage">Mileage of the  Maruti Suzuki S-Cross</h3>
                  <ul>
                    <li>
                      <h3>Petrol(MT)</h3>
                      <h4>18.55<span>km/l*</span></h4>
                    </li>
                    <li>
                      <h3>Petrol (AMT)</h3>
                      <h4>18.43<span>km/l*</span></h4>
                    </li>
          
                  </ul>
                  <p class="last-termsP"> The Maruti S-Cross mileage is 18.43 to 18.55 kmpl. The Manual Petrol variant has a mileage of 18.55 kmpl. The Automatic Petrol variant has a mileage of 18.43 kmpl.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="design">
  <div class="three60view">
    <picture class="front"> 
      
      <!--[if IE 9]><video style="display: none; "><![endif]-->
      
      <source srcset="assets/images/s-cross/3-desk.jpg" alt="s-cross" media="(min-width: 992px)">
      <source srcset="assets/images/s-cross/3-ipad.jpg" alt="s-cross" media="(min-width: 768px)">
      <source srcset="assets/images/s-cross/3-mobile.jpg" alt="s-cross" media="(min-width: 320px)">
      <!--[if IE 9]></video><![endif]--> 
      <img srcset="assets/images/s-cross/3-desk.jpg" alt="s-cross" class="resposive-img mainbg"> </picture>
    <section class="three60view-content col-lg-5">
      <section class="chase-description">
        <h2>THE S-Cross</h2>
        <p>Strong design lines and sharp angles of the new S-Cross gives the vehicle an upright masculine stance that never goes ignored.</p>
        <p>The Refined SUV - Powered by Next Generation Smart Hybrid Technology that adds to its Sophistication</p>
      </section>
    </section>
  </div>
</div>
<div class="container-fluid car-gallery">
  <ul class="nav nav-pills specification-tabs  d-flex justify-content-center" id="pills-tab" role="tablist">
    <li class="nav-item"> <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-body" role="tab" aria-controls="pills-home" aria-selected="true">Highlights</a> </li>
    <li class="nav-item"> <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-engine" role="tab" aria-controls="pills-profile" aria-selected="false">Exterior</a> </li>
    <li class="nav-item"> <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-transmission" role="tab" aria-controls="pills-contact" aria-selected="false"> Interior</a> </li>
  </ul>
  <div class="tab-content d-flex justify-content-center" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-body" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="row imageRow">
        <div class="col-lg-5 col-sm-5 col-xs-5 p-0">
          <div class="single first item-images"> <a href="assets/images/s-cross/highlights1.jpg" rel="lightbox[plants]" title="Click on the right side of the image to move forward."> <img src="assets/images/s-cross/highlights1.jpg" alt="s-cross" /> </a> </div>
        </div>
        <div class="col-lg-7 col-sm-7 col-xs-7">
          <div class="row">
            <div class="single item-images col-lg-8 col-sm-8 col-xs-8  p-0"> <a href="assets/images/s-cross/highlights2.jpg" rel="lightbox[plants]" title="Alternately you can press the right arrow key." > <img src="assets/images/s-cross/highlights2.jpg" alt="s-cross Automatic Climate Control" /> </a> </div>
            <div class="single item-images col-lg-4 col-sm-4 col-xs-4  p-0"> <a href="assets/images/s-cross/highlights3.jpg" rel="lightbox[plants]" title="The script preloads the next image in the set as you're viewing."> <img src="assets/images/s-cross/highlights3.jpg" alt="s-cross Rear AC Vent" /> </a> </div>
          </div>
          <div class="row">
            <div class="single item-images col-lg-4 col-sm-4 col-xs-4  p-0"> <a href="assets/images/s-cross/highlights4.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"> <img src="assets/images/s-cross/highlights4.jpg" alt="s-cross Rear Armrest" /> </a> </div>
            <div class="single item-images col-lg-8 col-sm-8 col-xs-8  p-0"> <a href="assets/images/s-cross/highlights5.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"> <img src="assets/images/s-cross/highlights5.jpg" alt="s-cross Refined Speedometer with Satin Chrome Meter Rings" /> </a> </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-engine" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div class="row imageRow">
        <div class="col-lg-5 col-sm-5 col-xs-5 p-0">
          <div class="single first item-images"> <a href="assets/images/s-cross/exterior1.jpg" rel="lightbox[plants]" title="Click on the right side of the image to move forward."> <img src="assets/images/s-cross/exterior1.jpg" alt="Ignis LED Projector Headlamps with DRLs" /> </a> </div>
        </div>
        <div class="col-lg-7 col-sm-7 col-xs-7">
          <div class="row">
            <div class="single item-images col-lg-8 col-sm-8 col-xs-8  p-0"> <a href="assets/images/s-cross/exterior2.jpg" rel="lightbox[plants]" title="Alternately you can press the right arrow key." > <img src="assets/images/s-cross/exterior2.jpg" alt="Ignis Fog Lamps with Chrome Fins" /></a> </div>
            <div class="single item-images col-lg-4 col-sm-4 col-xs-4  p-0"> <a href="assets/images/s-cross/exterior3.jpg" rel="lightbox[plants]" title="The script preloads the next image in the set as you're viewing."> <img src="assets/images/s-cross/exterior3.jpg" alt="Ignis Precision-cut Two-tone Alloy Wheels" /></a> </div>
          </div>
          <div class="row">
            <div class="single item-images col-lg-4 col-sm-4 col-xs-4  p-0"> <a href="assets/images/s-cross/exterior4.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"> <img src="assets/images/s-cross/exterior4.jpg" alt="Ignis Fog Lamps With Bold Chrome Accents" /> </a> </div>
            <div class="single item-images col-lg-8 col-sm-8 col-xs-8  p-0"> <a href="assets/images/s-cross/exterior5.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"> <img src="assets/images/s-cross/exterior5.jpg" alt="Ignis LED Projector Headlamps & DRLs" /> </a> </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-transmission" role="tabpanel" aria-labelledby="pills-contact-tab">
      <div class="row imageRow">
        <div class="col-lg-5 col-sm-5 col-xs-5 p-0">
          <div class="single first item-images"> <a href="assets/images/s-cross/interior1.jpg" rel="lightbox[plants]" title="Click on the right side of the image to move forward."> <img src="assets/images/s-cross/interior1.jpg" alt="s-cross" /> </a> </div>
        </div>
        <div class="col-lg-7 col-sm-7 col-xs-7">
          <div class="row">
            <div class="single item-images col-lg-8 col-sm-8 col-xs-8  p-0"> <a href="assets/images/s-cross/interior2.jpg" rel="lightbox[plants]" title="Alternately you can press the right arrow key." > <img src="assets/images/s-cross/interior2.jpg" alt="s-cross" /> </a> </div>
            <div class="single item-images col-lg-4 col-sm-4 col-xs-4  p-0"> <a href="assets/images/s-cross/interior3.jpg" rel="lightbox[plants]" title="The script preloads the next image in the set as you're viewing."> <img src="assets/images/s-cross/interior3.jpg" alt="s-cross" /> </a> </div>
          </div>
          <div class="row">
            <div class="single item-images col-lg-4 col-sm-4 col-xs-4  p-0"> <a href="assets/images/s-cross/interior4.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"> <img src="assets/images/s-cross/interior4.jpg" alt="s-cross" /> </a> </div>
            <div class="single item-images col-lg-8 col-sm-8 col-xs-8  p-0"> <a href="assets/images/s-cross/interior5.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"> <img src="assets/images/s-cross/interior5.jpg" alt="s-cross" /> </a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="spcification2">
  <div class="container">
    <h2>Specification</h2>
    <div class="row ">
      <div class="col-lg-3 col-md-3 col-sm-12">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical"> 
        <a class="nav-link active" id="v-pills-dimensions-tab" data-toggle="pill" href="#v-pills-dimensions" role="tab" aria-controls="v-pills-dimensions" aria-selected="true">Dimensions</a> 
        <a class="nav-link" id="v-pills-engine-tab" data-toggle="pill" href="#v-pills-engine" role="tab" aria-controls="v-pills-engine" aria-selected="false">Engine</a> 
        <a class="nav-link" id="v-pills-brakes-tab" data-toggle="pill" href="#v-pills-brakes" role="tab" aria-controls="v-pills-brakes" aria-selected="false">Brakes</a>
         <a class="nav-link" id="v-pills-weight-tab" data-toggle="pill" href="#v-pills-weight" role="tab" aria-controls="v-pills-weight" aria-selected="false">Wheels & Tyres</a> 
         <a class="nav-link" id="v-pills-transmission-tab" data-toggle="pill" href="#v-pills-transmission" role="tab" aria-controls="v-pills-transmission" aria-selected="false">Fuel & Performance</a>
          </div>
      </div>
      <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="tab-content" id="v-pills-tabContent">
          <div class="tab-pane fade show active" id="v-pills-dimensions" role="tabpanel" aria-labelledby="v-pills-dimensions-tab">
            <ul class="spc-details">
            <li><span>Length </span>4300(mm)</li>
            <li><span>Width </span>1785(mm)</li>
            <li><span>Height </span>1595(mm)</li>
            <li><span>Seating Capacity</span>5</li>
            <li><span>Wheel Base </span>2600(mm)</li>
            <li><span>Kerb Weight (Kg)</span>1130-1170</li>
            <li><span>Gross Weight (Kg)</span> 1640</li>
            <li><span> No of Doors</span> 5</li>
            </ul>
          </div>
          <div class="tab-pane fade" id="v-pills-engine" role="tabpanel" aria-labelledby="v-pills-engine-tab">
            <ul class="spc-details">
              <li><span> Engine Type</span> K15B Smart Hybrid</li>
                <li><span>Displacement (cc)</span>1462</li>
                <li><span> Max Power</span> 103.26bhp@6000rpm</li>
                <li><span> Max Torque</span>138nm@4400rpm</li>
                <li><span> No. of cylinder</span>4</li>
                <li> <span>Valves Per Cylinder</span>4</li>
                <li><span>Bore X Stroke</span>74.0 x 85.0</li>
                <li><span> TransmissionType</span>Automatic</li>
                <li><span> Gear Box</span>4</li>
                <li><span>Mild Hybrid</span>Yes</li>
                <li><span>Drive Type</span>2WD</li>

            </ul>
          </div>
          <div class="tab-pane fade" id="v-pills-brakes" role="tabpanel" aria-labelledby="v-pills-brakes-tab">
            <ul class="spc-details">
              <li><span> Front Suspension</span> McPherson Strut with coil spring</li>
              <li><span> Rear Suspension</span> Torsion Beam with coil spring</li>
              <li><span> Turning Radius (Metres)</span> 5.5</li>
              <li><span> Front Brake Type</span>	Ventilated Disc</li>
               <li><span> Rear Brake Type</span>	Solid Disc</li>
            </ul>
          </div>
          <div class="tab-pane fade" id="v-pills-weight" role="tabpanel" aria-labelledby="v-pills-weight-tab">
            <ul class="spc-details">
              <li><span> Wheel Type</span> Machined Alloy Wheels</li>
              <li><span> Tyre Type</span> Tubeless, Radial</li>
              <li><span> Front Tyre Size</span> 215/60 R16</li>
              <li><span> Rear Tyre Size</span> 215/60 R16</li>
            </ul>
          </div>
          
          <div class="tab-pane fade" id="v-pills-transmission" role="tabpanel" aria-labelledby="v-pills-transmission-tab">
            <ul class="spc-details">
             <li><span> Fuel Type</span> Petrol</li>
              <li><span> Mileage (ARAI)</span> 18.43</li>
              <li><span> Fuel Tank Capacity (Litres)</span> 48</li>
              <li><span> Emission Norm Compliance</span> BS VI</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="img-car"> <img src="assets/images/s-cross/4-ciaz.png" alt="carFooter"> </div>
  </div>
</div>
<div class="performance2">
  <div class="performnace-bg">
    <picture>
      <source srcset="assets/images/s-cross/5-desk.jpg" alt="Baleno performance" media="(min-width: 992px)">
      <source srcset="assets/images/s-cross/5-ipad.jpg" alt="Baleno performance" media="(min-width: 768px)">
      <source srcset="assets/images/s-cross/5-mobile.jpg" alt="Baleno performance" media="(min-width: 320px)">
      <img srcset="assets/images/s-cross/5-desk.jpg" alt="Baleno performance" class="img-responsive bg-image"></picture>
    <div class="col-lg-6 col-md-3 col-sm-6 col-xs-12 prod-image"> <img src="assets/images/s-cross/5-engine.png" class="" alt="Baleno Engine"> </div>
    <div class="performance-content col-xs-12 col-sm-6 col-md-9 col-lg-6">
      <h2>Features</h2>
      <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-12">
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical"> 
          <a class="nav-link active" id="v-pills-exterior-tab" data-toggle="pill" href="#v-pills-exterior" role="tab" aria-controls="v-pills-exterior" aria-selected="true">Safety & Security</a> 
          <a class="nav-link" id="v-pills-interiors-tab" data-toggle="pill" href="#v-pills-interiors" role="tab" aria-controls="v-pills-interiors" aria-selected="false">Comfort & Convenience</a> 
          <a class="nav-link" id="v-pills-safety-tab" data-toggle="pill" href="#v-pills-safety" role="tab" aria-controls="v-pills-safety" aria-selected="false">Instrumentation & Communication</a>
          </div>
        </div>
        <div class="col-lg-9 col-md-8 col-sm-12">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-exterior" role="tabpanel" aria-labelledby="v-pills-exterior-tab">
              <ul class="features-content">
                <li>Anti-Lock Braking System</li>
                <li>Brake Assist</li>
                <li>Central Locking</li>
                <li>Power Door Locks</li>
                <li>Child Safety Locks</li>
                <li>Anti-Theft Alarm</li>
                <li>Seat Belt Warning</li>
                <li>Door Ajar Warning</li>
                <li>Side Impact Beams</li>
                <li>Engine Immobilizer</li>
                <li>Crash Sensor</li>
                <li>Centrally Mounted Fuel Tank</li>
                <li>Engine Check Warning</li>
                <li>Automatic Headlamps</li>
              </ul>
            </div>
            <div class="tab-pane fade" id="v-pills-interiors" role="tabpanel" aria-labelledby="v-pills-interiors-tab">
              <ul class="features-content">
                <li> Cruise Control</li>
                <li> Navigation System</li>
                <li> Power Boot</li>
                <li> Smart Access Card Entry</li>
                <li>Voice Control</li>
                <li> Adjustable Steering</li>
                <li>Automatic Climate Control</li>
                <li>Remote Trunk Opener</li>
                 <li>Accessory Power Outlet</li>
                  <li>Trunk Light</li>
                   <li>Vanity Mirror</li>
                    <li>Adjustable Headrest</li>
                     <li>Height Adjustable Front Seat Belts</li>
                     <li>Soft Touch IP, Dust & Pollen Filter, Engine Auto Start-Stop Cancel Switch, Electric Back Door Opening, Driver Side Footrest, Sunglass Holder, Reclining Rear Seat, Vanity Mirror Lamps</li>
                
              </ul>
            </div>
            
            <div class="tab-pane fade" id="v-pills-safety" role="tabpanel" aria-labelledby="v-pills-safety-tab">
              <ul class="features-content">
                <li>Steering Mounted Audio & Calling Controls</li>
                <li>Bluetooth + USB + AUX IN Connectivity</li>
                <li>Door Speakers (4)</li>
                <li>Audio with CD Player</li>
                <li>Audio Remote Control</li>
                <li>17.8 cm Touchscreen SmartPlay Studio</li>
                <li>Voice Command</li>
                <li>Apple CarPlay / Android Auto*</li>
                <li>Remote Control through Smartphone App.</li>
                <li>Navigation System with Live Traffic Update (Through Smartplay Studio App)</li>
                <li>Tweeters (2)</li>
              </ul>
              <p style="color:#FFF"> *Android Auto is TM of Google and Apple CarPlay is TM of Apple Inc.</p>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="myCarousel" class="carousel slide footer-banner2" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active"> <img class="first-slide" src="assets/images/s-cross/slide1.png" alt="Luxurious Interiors">
      <div class="caption">
        <h2>S-Cross<span> Technology</span></h2>
        <p> The Refined SUV - Powered by Next Generation Smart Hybrid Technology that adds to its Sophistication</p>
      </div>
    </div>
    <div class="carousel-item"> <img class="second-slide" src="assets/images/s-cross/slide2.png"  alt="Smart Hybrid Technology">
      <div class="caption">
        <h2>LED Rear Combination <span>Lamp</span></h2>
        <p>  The rear of the vehicle adds a sharp aesthetic to the new S-Cross Petrol, thanks to the LED Rear Combination Lamps whose streamlined design exudes a sophisticated aura.</p>
      </div>
    </div>
    <div class="carousel-item"> <img class="second-slide" src="assets/images/s-cross/slide3.png"  alt="Automatic Transmission">
      <div class="caption">
        <h2>Sophisticated <span>Interiors</span></h2>
        <p>Rugged on the outside, luxurious and comfortable on the inside. The Refined SUV makes sure you experience exemplary space and comfort in every drive.</p>
      </div>
    </div>
    <div class="carousel-item"> <img class="second-slide" src="assets/images/s-cross/slide4.png"  alt="SmartPlay Infotainment System">
      <div class="caption">
        <h2>Introduction to <span>Automatic Transmission</span></h2>
        <p> The new S-Cross Petrol takes on sharp turns, steep climbs and rough roads with the ease of Automatic Transmission with Hill Hold assist. </p>
      </div>
    </div>
    <div class="carousel-item"> <img class="second-slide" src="assets/images/s-cross/slide5.png"  alt="NEXA Safety Shield">
      <div class="caption">
        <h2>AUTO RAIN SENSING <span>WIPERS</span></h2>
        <p> The Auto Rain Sensing Wipers in the Refined SUV detects rain and starts automatically. The frequency is regulated according to the amount of rainfall, and the rain sensitivity can also be controlled. </p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
</main>

<!--Get A Quote Modal -->
<div class="get-quotePopup modal fade" id="get-quotePopup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Get A Quote</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
      </div>
      <form action="send_mail_quotation.php" method="post" data-parsley-validate="parsley" onsubmit="return submitUserForm();">
        <div class="modal-body">
          <div class="form-group">
            <label for="First Name" class="col-form-label">Full Name<span class="parsley-required">*</span></label>
            <input type="text" class="form-control" id="first-name" name="full_name" required="true" data-parsley-pattern="^[a-zA-Z.,/ $()]+$" data-parsley-pattern-message="Name should be in text only" data-parsley-required-message="Please Enter Name">
            <input type="hidden" class="form-control" name="model" id="model" value="Ignis">
          </div>
          <div class="form-group">
            <label for="Email" class="col-form-label">Email<span class="parsley-required">*</span></label>
            <input type="email" class="form-control" id="Email" name="email" required="true" data-parsley-type="email" data-parsley-required-message="Please Enter Email Id">
          </div>
          <div class="form-group">
            <label for="Phone" class="col-form-label">Phone<span class="parsley-required">*</span></label>
            <input type="tel" class="form-control" id="phone" name="phone_no" required="true" data-parsley-type="digits" maxlength="10" data-parsley-pattern=^[6-9]\d{9}$ data-parsley-pattern-message="Mobile no should starts with 6/7/8/9 AND 10 Digit" data-parsley-required-message="Please Enter Contact No">
          </div>
          <div class="form-group">
            <label for="inputAddress2">City<span class="parsley-required" style="color:red">*</span></label>
            <select class="form-control city" required="true"  aria-required="true" aria-invalid="false" name="city" id="city" onchange="check(event);">
              <option value="Nagpur">Nagpur</option>
              <option value="Nanded">Nanded</option>
              <option value="Nashik">Nashik</option>
            </select>
          </div>
          <div class="form-group">
            <div class="g-recaptcha" data-sitekey="6LcuUwEVAAAAAOF4b4IxvoXTo3TN09aaviVw2xaw" data-callback="verifyCaptcha"></div>
            <div id="g-recaptcha-error"></div>
          </div>
          <div class="form-group">
            <p style="font-size:12px"><span class="parsley-required">*</span>
              <input type="checkbox" id="FormChkBoxBook6" name="FormChkBox" style="vertical-align: sub;" required="true" data-parsley-required-message="Please indicate that you accept the Terms and Conditions">
              I agree <a href="disclaimer.php" style="color: blue">Terms and Conditions.</a> by clicking the ‘Continue’ button below and I am explicitly soliciting a call from Seva Maruti. Or its partners on my ‘Mobile’.</p>
          </div>
        </div>
        <div class="modal-footer d-flex justify-content-between">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" name="submit" class="btn btn-primary">
      </form>
    </div>
  </div>
</div>
</div>
<!--Get A Quote Modal --> 
<script src='https://www.google.com/recaptcha/api.js'></script> 
<script src="assets/js/jquery1.12.0-min.js"></script> 
<script src="assets/js/parsley.js"></script> 
<script src="assets/js/lightbox.js"></script> 
<script>
// document.getElementById('g-recaptcha-error').innerHTML = 'block';
function submitUserForm() {
    var response = grecaptcha.getResponse();
    // alert(response);die();
    if(response.length == 0) {
        document.getElementById('g-recaptcha-error').innerHTML = '<span style="color:red;">This field is required.</span>';
        return false;
    }
    return true;
}
 
function verifyCaptcha() {
    document.getElementById('g-recaptcha-error').innerHTML = '';
}
</script>
<?php  


require_once('footer.php');

?>
